FROM node:21-alpine AS development

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .

#RUN yarn install
RUN npm install

# Copy app files
COPY . .

# Start the app
CMD [ "yarn", "dev" ]
