version: "3.8"

services:
  app-development:
    container_name: chess-web-dev
    image: chess-web-dev-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
